
build:
  info:
    - echo "Env:" ; env
    - echo <% print "CHUL" %>

  run:
    - cd /app
    - npm test

#plugins:
#- docker_publish:
#    repository: index.dev.chappy.co
#    name: test/test
#    tag: $DOTCI_SHA
