build:
  info:
    - echo "Env:" ; env
    - echo ${BUILD_ID}
    - echo ${JOB_NAME}
    - echo ${BUILD_TAG}
    - echo ${BUILD_NUMBER}

  run:
    - cd /app
    - npm test

#plugins:
#- docker_publish:
#    repository: index.dev.chappy.co
#    name: test/test
#    tag: $DOTCI_SHA
